### ISSUE TITLE
Crypto1 implementation

### ISSUE THREAD

**Issue by ghost** [emsec/ChameleonMini#109]
As many of you know, the crypto1 implementation in master branch is pretty bad.
Did anyone try to replace the current implementation with the one from tools like mfuk or mfoc, where timing is a lot more important? 

Any positive results?

**Comment by geo-rg** [comment]
Have you tried the [MFClassic_patch branch](https://github.com/emsec/ChameleonMini/tree/MFClassic_patch)? Make sure to compile after switching to this branch.

**Comment by geo-rg** [comment]
We have now updated the master branch and to our knowledge MF Classic emulation now works pretty good.

I will close this issue since the user ghost has deleted himself.
