### ISSUE TITLE
Info about Rev. F, G

### ISSUE THREAD

**Issue by x893** [emsec/ChameleonMini#11]
Hello,
perfect project !

Can you say about time to update to Rev. F or G ?

Best wishes
Mitek

**Comment by timokasper** [comment]
update to revg comes with the shipping, probably end of september / beginning of October
 
TK


 
Von: Mitek [mailto:notifications@github.com] 
Gesendet: Freitag, 16. September 2016 02:56
An: emsec/ChameleonMini <ChameleonMini@noreply.github.com>
Betreff: [emsec/ChameleonMini] Info about Rev. F, G (#11)
 
Hello,
perfect project !
Can you say about time to update to Rev. F or G ?
Best wishes
Mitek
