### ISSUE TITLE
Chameleon log haven't Nt nonce

### ISSUE THREAD

**Issue by maxben14** [emsec/ChameleonMini#111]
Chameleon log haven't Nt nonce.
30538 ms <    +9 ms>:CODEC RX         (4   bytes) [6000f57b] auth
30540 ms <    +2 ms>:CODEC RX         (8   bytes) [80e7d2e3e038c300] nr ar
30549 ms <    +9 ms>:CODEC RX         (4   bytes) [c90a5b66]
30556 ms <    +7 ms>:CODEC RX         (4   bytes) [500057cd]
....
30679 ms <   +88 ms>:CODEC RX         (4   bytes) [6000f57b]
30681 ms <    +2 ms>:CODEC RX         (8   bytes) [cf2094db47a07fa2]
30688 ms <    +7 ms>:CODEC RX         (4   bytes) [e58d3449]
30698 ms <   +10 ms>:CODEC RX         (4   bytes) [6210d77e]

How restore key without Nt nonce ?
I want use mfkey32 but this tools need Nt nonce.

**Comment by geo-rg** [comment]
Please refer to [this comment](https://github.com/emsec/ChameleonMini/issues/110#issuecomment-304198299).
