### ISSUE TITLE
Emulation Mifare Classic

### ISSUE THREAD

**Issue by maxben14** [emsec/ChameleonMini#112]
I want to do a log when a chameleon emulates a mifare classic. I want to log the nonces Nt, Nr, Ar. Prompt please the command for logging nonces from the implementation of crypto1.

**Comment by geo-rg** [comment]
As you can read at [this page](https://rawgit.com/emsec/ChameleonMini/master/Doc/Doxygen/html/Page_CommandLine.html) of our documentation, you may set `logmode=memory` and later get the log with `logdownload`. You will have to find the nonces by yourself from that log.

You may also use the chamlog tool from the Software folder of this repository.

**Comment by maxben14** [comment]
I get errors during the emulation of the mifare classic.
The chameleon emulates ultralights well, but produces errors when emulating the mifare classic.

**Comment by geo-rg** [comment]
@maxben14 Have you tried the last versions of the Firmware? We have fixed some bugs.

**Comment by geo-rg** [comment]
I assume your problem is solved, just re-open this thread if you have any new related problems.
