### ISSUE TITLE
Chameleon memory problem

### ISSUE THREAD

**Issue by Peterthegreat** [emsec/ChameleonMini#113]
Hello,
So this is a pretty annoying issue. The memory of the IC somehow gets corrupted (mostly if you power it off during startup). The ChameleonMini is not responding - the LEDs power off and not seen on USB. To reproduce the problem, (optional? load some data to be emulated) toggle the power switch fast a couple of times.

I am uploading the boot-loader with an USBASP, using this config for the IC:

part parent ".xmega"
    id      = "x128a4u";
    desc    = "ATxmega128A4U";
    signature   = 0x1e 0x97 0x46;
//    usbpid  = 0x2fde;
 
    memory "eeprom"
        size        = 0x800;
        offset      = 0x8c0000;
        page_size   = 0x20;
        readsize    = 0x100;
    ;
 
    memory "application"
        size        = 0x20000;
        offset      = 0x800000;
        page_size   = 0x100;
        readsize    = 0x100;
    ;
 
    memory "apptable"
        size        = 0x1000;
        offset      = 0x81f000;
        page_size   = 0x100;
        readsize    = 0x100;
    ;
 
    memory "boot"
        size        = 0x00002000;
        offset      = 0x00820000;
        page_size   = 0x100;
        readsize    = 0x100;
    ;
 
    memory "flash"
        size        = 0x22000;
        offset      = 0x800000;
        page_size   = 0x100;
        readsize    = 0x100;
    ;
 
    memory "usersig"
        size        = 0x100;
        offset      = 0x8e0400;
        page_size   = 0x100;
        readsize    = 0x100;
    ;
;
`
Then I upload the code via USB with "ChameleonFirmwareUpgrade.bat"

I don't know sure if the problem is in the flash, in the EEPROM or somewhere else, but one time while having this issue the Chameleon got into boot-loader mode and I was able to rewrite the memory. First I uploaded only the EEPROM.
```
"%~dp0dfu-programmer.exe" atxmega128a4u flash-eeprom "%~dp0Chameleon-Mini.eep" --force
"%~dp0dfu-programmer.exe" atxmega128a4u launch
```
 This did not made any difference, the LEDs where still off, and the Chameleon was still in boot-loader mode. Then I uploaded only the flash, and the result was the same.

To make it work, I have to erase the IC and rewrite the boot-loader and the flash+EEPROM 

Things that I have tried: 

- different firmware "ChameleonMini RevG 161024 using LDFA 151115 compiled with AVR-GCC 4.9.2" 
  (but the same boot-loader version bootloader-atxmega128a4u-104-PA6-SPM)
- replace C1 and C2 with higher values (10u)
- replace the IC with a new one

Attached are the eeprom and flash of the IC when this issue happens

[dead-FLASH.hex.txt](https://github.com/emsec/ChameleonMini/files/1048440/dead-FLASH.hex.txt)
[dead-EEPROM.eep.txt](https://github.com/emsec/ChameleonMini/files/1048441/dead-EEPROM.eep.txt)

My guess is that my power on switch has imperfect contacts and sometimes an on-off toggle is happening while powering on the ChameleonMini. I will replace the switch but it doesn't guarantee that it won't happen again.

**Comment by Peterthegreat** [comment]
Also, when this happens, there is no 13.56mhz signal on the oscilator

**Comment by Peterthegreat** [comment]
The problem appeared again, this time after using chamlog.py. First the chamlog did not respond, so i did a restart. Then the PC could not see the Chameleon on USB. After another restart, the device was in bootloader mode. I took the chance and uploaded the EEPROM, without erasing the chip first.
![image](https://cloud.githubusercontent.com/assets/4208549/26816484/78919e20-4a9a-11e7-8ca6-9b8274ded177.png)

This made the device disappear from USB, but after pressing RBTN, it was back to bootloader mode.

Then I uploaded the .hex, again without an initial erase:
![image](https://cloud.githubusercontent.com/assets/4208549/26816472/67dfaa36-4a9a-11e7-994f-770287be37b6.png)

 
And then with --force argument:
![image](https://cloud.githubusercontent.com/assets/4208549/26816375/eca099fc-4a99-11e7-8108-bb8f5c49f003.png)

And the device was seen via USB. I will now reproduce the problem and will try to upload the flash memory first (.hex)

**Comment by Peterthegreat** [comment]
Ok, so that writing without erasing the chip did not lasted long. While trying to reproduce the problem with the on/off toggle, the device was not recognize anymore (VID&PID)
![image](https://cloud.githubusercontent.com/assets/4208549/26817602/da7b1738-4a9f-11e7-8915-519960eb7a54.png)

After a few more attempts, the correct com was shown and this is what the gui shows
![image](https://cloud.githubusercontent.com/assets/4208549/26818176/53ed56b0-4aa2-11e7-8a6e-1b1088266514.png)

After resetting the comunication, the device is unrecognized again.

**Comment by Peterthegreat** [comment]
./avrdude -C avrdude.conf -c usbasp -p x128a4u -U flash:v:bootloader-atxmega128a4u-104-PA6-SPM.hex:i -E noreset

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e9746
avrdude: NOTE: Programmer supports page erase for Xmega devices.
         Each page will be erased before programming it, but no chip erase is performed.
         To disable page erases, specify the -D option; for a chip-erase, use the -e option.
avrdude: verifying flash memory against bootloader-atxmega128a4u-104-PA6-SPM.hex:
avrdude: load data flash data from input file bootloader-atxmega128a4u-104-PA6-SPM.hex:
avrdude: input file bootloader-atxmega128a4u-104-PA6-SPM.hex contains 139252 bytes
avrdude: reading on-chip flash data:

Reading | ################################################   | 95% 1.25savrdude: paged_load failed
avr_read(): error reading address 0x20000
    read operation not supported for memory "flash"
avrdude: failed to read all of flash memory, rc=-2


Obvious, the eeprom/flash verify will fail since I upload some data to the slots.

**Comment by geo-rg** [comment]
Sorry for the late reply.
We really could not reproduce your problem. Have you tried to replace your power switch? However, I cannot imagine how a bad contact on the power switch would cause memory corruptions within the flash memory. Have you gained any new information on your problem?

**Comment by Peterthegreat** [comment]
No worries.
Do you think that my method of programming the IC is ok? I am using a patched fw for my USBASP that allows me to write to Xmega cips, but I am using it only to upload the bootloader, and avrdude verificiation step shows that is done correctly. The UpdateFirmware.bat uses USB and also has an erase command before writing the flash.

**Comment by Peterthegreat** [comment]
I did not changed the power switch yet. Meanwhile, I will try my best to find exactly why this is happening, so you can reproduce the problem. Thank you for the support

**Comment by Peterthegreat** [comment]
Just changed the power switch and I still get the random "death" of the board. Since I am the only one having this problem, I will recheck the values from the BoM

**Comment by skuep** [comment]
Can you give the microcontrollers fuse settings? Maybe the brown out detector is not correctly configured.

**Comment by Peterthegreat** [comment]
avrdude -v option doesn't show the fuse bits, I will have to get them some other way. I did not changed the default fuse settings

**Comment by Peterthegreat** [comment]
I am not sure this is correct, but here is my attempt:
fuse0: 0xff
fuse1: 0x0
fuse2: 0xff
fuse4: 0xfe
fuse5: 0xff

**Comment by Peterthegreat** [comment]
Rechecked the BoM and everything looks fine (I have an equivalent for D5). Did a reflow on the left part of the board, but the problem is still there. Next step I will try a bigger value for C8 and C9 (input and output of the 3.3 voltage regulator)

**Comment by geo-rg** [comment]
@Peterthegreat The Fuses you have set are not correct. Just try these:
fuse1: 0x00
fuse2: 0xBE
fuse4: 0xF3
fuse5: 0xED

**Comment by Peterthegreat** [comment]
I would gladly try those fuse settings, but first, can you please confirm I got the memory address right? Here is my avrdude config:

` 
memory "fuse0"
        size		= 1;
        offset		= 0x8f0020;
    ;

    memory "fuse1"
        size		= 1;
        offset		= 0x8f0021;
    ;

    memory "fuse2"
        size		= 1;
        offset		= 0x8f0022;
    ;

    memory "fuse4"
        size		= 1;
        offset		= 0x8f0024;
    ;

    memory "fuse5"
        size		= 1;
        offset		= 0x8f0025;
    ;`

**Comment by Peterthegreat** [comment]
Forgot to post an update. Changed Q1 and got bigger values for C8 and C9, but did not solved anything, except a slightly better read from my phone's NFC . Now I uploaded the fuse bit configuration. Will post the results

**Comment by Peterthegreat** [comment]
That was it! No idea how the fuse bits got changed.. Maybe they were wrong form the start. I got the problem a long time ago, but only recent had time to play more intensively with the chameleon. 

Thank you guys, now I can focus on closing the other issues.
