### ISSUE TITLE
TNP3xxx Application

### ISSUE THREAD

**Issue by Symon998** [emsec/ChameleonMini#119]
Any possibility of TNP3xxx application compatibility?

**Comment by doegox** [comment]
It's already compatible as such with normal MFC emulation.

**Comment by Symon998** [comment]
Hi Philippe,

Thanks for the response on this, when configuring the card to MF_Classic_1K any dumps sent to the card fail when dump originally from TNP3xxx

Any help would be great thanks

Simon Buchanan

On 18 Jun 2017, at 11:07, Philippe Teuwen <notifications@github.com<mailto:notifications@github.com>> wrote:


It's already compatible as such with normal MFC emulation.

**Comment by geo-rg** [comment]
Hi @Symon998 
recently there have been some fixes for Mifare Classic emulation, please try if these solve your problems.

**Comment by Symon998** [comment]
Hi @geo-rg
Will take a look and update firmware tonight - will respond on outcome

Any specific details on what the fixes are that went in and when they were updated with MFC? As I had flashed with latest firmware available last week?

Thanks geo-rg

**Comment by geo-rg** [comment]
The updates have been done Wednesday last week and this week. There was one update within the emulation codec and various updates within the Mifare Classic 4K emulation. See also [here](https://github.com/emsec/ChameleonMini/commits/master).

**Comment by geo-rg** [comment]
@Symon998 Did the updates solve your problems?

**Comment by geo-rg** [comment]
I assume the updates solved your problems. If not so, please simply re-open this issue.
