### ISSUE TITLE
MFClassic emulation error

### ISSUE THREAD

**Issue by Peterthegreat** [emsec/ChameleonMini#121]
Just tried the latest version on the master branch that supposed to contain the mifare1K patch, but seems that it still has some errors. Here is the log:

![image](https://user-images.githubusercontent.com/4208549/27496373-5c7dfe6e-585e-11e7-92b3-9f6cafd22fc4.png)

Also, there is no "ar" inside the log. Can somebody confirm this?
BTW, the MFClassic branch works in the same testing environment.

**Comment by Peterthegreat** [comment]
I must mention that I uploaded the pre-compiled files, because they were added a few days ago. I will compile the source again and post an update

**Comment by Peterthegreat** [comment]
Recompiled the source, and the result is similar. My phone's nfc dose not recognize an emulated tag. Here is the emulation log. 
![image](https://user-images.githubusercontent.com/4208549/27633564-6824314a-5c08-11e7-91c7-6710ecf2c5a4.png)

There is something wrong with the latest build.

**Comment by geo-rg** [comment]
Indeed, the reader does not respond to the Chameleon after sending the "cards" nonce and the Chameleon interprets the readers re-try as the reading continuing the authentication and everything goes wrong.
Which reader are you using?

**Comment by Peterthegreat** [comment]
Right now, the reader from a public bus (first post) and the one from my phone is a Broadcom chip (second post). I will post the test from my PN532 later

**Comment by geo-rg** [comment]
@Peterthegreat We cannot reproduce these errors. Is it possible that you use a self-built Chameleon? Then I would also take hardware errors into consideration.

**Comment by Peterthegreat** [comment]
@geo-rg Yes. I am using a self-build Chameleon. In this post I tried the latest master branch, but using an older version of MFClassic_patch works perfectly fine with the hardware.

**Comment by geo-rg** [comment]
Has your Fuse fix also solved this problem?

**Comment by Peterthegreat** [comment]
Flashed the latest version. The log from PN532 looks good, but I think that worked even before the MFClassic_patch. I will try the reader that gave errors as soon as I have access to it.

**Comment by Peterthegreat** [comment]
Although I was unable to store the log (even with Lbutton config set to store_log), the emulation finally worked (took 4 tries before it was recognized)
