### ISSUE TITLE
Base ChameleonMini on Raspberry Pi ?

### ISSUE THREAD

**Issue by Paulymorphe** [emsec/ChameleonMini#122]
Does anyone knows if it is possible to base the ChameleonMini on Raspberry Pi instead of Atmel ?

**Comment by david-oswald** [comment]
Porting the full Chameleon codebase to a Pi is likely impossible due to the necessary real-time code. You can however connect the Chameleon to a Pi via the USB terminal.

**Comment by geo-rg** [comment]
Hi @Paulymorphe 
is your question answered or do you have further questions?

**Comment by Paulymorphe** [comment]
Yeah @geo-rg, I was thinking about porting the Chameleon to Pi as I don't have the necessary stuff to make SMD. It isn't possible using a Pi but what do you think about an Arduino, as it's also based under an Atmel...
