### ISSUE TITLE
Request for Cryptographic Function

### ISSUE THREAD

**Issue by shinestarqiao** [emsec/ChameleonMini#123]
Hi, I have bought ChameleonMIni and want to do something about cryptographic.
Do you have some library files for popular encryption methods, like AES and DES?
Thanks a lot.

**Comment by geo-rg** [comment]
Have a look at the [fork of dev-zzo](https://github.com/dev-zzo/ChameleonMini/). For DESFire emulation, he has 3DES implemented.

I'm curious, what are you planning to do? :)

**Comment by shinestarqiao** [comment]
Thanks for your help. Actually I want to implement some encryption codes into the tag to measure the delay time.

**Comment by geo-rg** [comment]
So, how exactly can I help you? Or did my answer already answer your question fully?

**Comment by geo-rg** [comment]
@shinestarqiao I suppose your question has been answered. If not so, please re-open this issue.
