### ISSUE TITLE
printf output

### ISSUE THREAD

**Issue by Caydenz** [emsec/ChameleonMini#129]
Hi,

Where is the printf output redirected? I am trying to debug some changes and using LogEntries is pretty horrible.

Thanks!

**Comment by geo-rg** [comment]
Hi @Caydenz,
you cannot use printf to send data via Terminal, instead you may use TerminalSendString and snprintf, since TerminalSendString solely takes a string and no other parameters.

**Comment by skuep** [comment]
Actually, if I remember correctly, LUFA gives some Support with CDC ACM and streams and stdout.. 
See here 
http://fourwalledcubicle.com/blog/2009/11/lufa-cdc-streams/

Am 31. Juli 2017 09:14:26 MESZ schrieb Georg Land <notifications@github.com>:
