### ISSUE TITLE
what is the Chameleon-Mini.bin use for?

### ISSUE THREAD

**Issue by feifeilanniao** [emsec/ChameleonMini#132]
There is a file named Chameleon-Mini.bin in the path :"ChameleonMini-master\RevE\Firmware\Chameleon-Mini",is this a Application flie which use to upgrade the firmware?

**Comment by geo-rg** [comment]
First of all: have you noticed, that this file is in the RevE folder and thus has nothing to do with the RevG Chameleon?

The .bin files are just another type of representation and (I think) they can also be used for flashing. The usual way is to simply use the hex file.

**Comment by feifeilanniao** [comment]
Yes,i have a RevE Chameleonimi.And i want to use this .bin files.
