### ISSUE TITLE
Logging KeyA and KeyB requests

### ISSUE THREAD

**Issue by yaba** [emsec/ChameleonMini#133]
I'm studying a system that generates KeyA and KeyB based on UID.
Is Chameleon Mini capable of generating a couple of sequential UIDs and log the keys used to read the sectors (except KeyA from sector0 since this is a fixed one)?
For example, let's say I know that for UID 00112233 machine will use KeyA 010203040506.
I need to understand what key the machine will use if I use pre-defined UID like 11223344 and log that that request.

**Comment by emsec** [comment]
ChameleonMini can generate different UIDs and log the communication, you can a) control it from a PC e.g. with a Python script (see python folder in the chameleon github project for an example script)  or b) change the firmware accordingly but I think a) is the better option for you. 
 
configure as CONFIG=MF_CLASSIC_1k and then use the UID command to set the UID, e.g., UID=11223344
 
Next, use the chamlog tool in the github project to get the log in human-readable form.

However, note that cryptographic keys are NEVER sent during an authentication (that's the whole idea of a Challenge-Response protocol as used in the Mifare Classic cards...) so you cannot log the keys directly, but for each new UID you would have to crack the keys, somehow....  (It is technically feasible to find the keys from logging the communicaion but this topic is too big to be discussed here...)

**Comment by Peterthegreat** [comment]
@yaba I was working on this a while back. PM me as I don't want to publish the code just yet.

**Comment by yaba** [comment]
@Peterthegreat github doesn't allow PM anymore, can I use the emsec e-mail ?

**Comment by Peterthegreat** [comment]
@yaba Guess so. I have no idea how that works.

**Comment by leperjulien** [comment]
@Peterthegreat 
Actually , i might also be interested if you don't mind !
That would be a great opportunity to take my ChameleonMini out of the drawer since it has been laying there for quite some time now.

**Comment by geo-rg** [comment]
@yaba I suppose everything is clear now, if not so, please re-open this issue.
