### ISSUE TITLE
Firmware Upgrade Issue

### ISSUE THREAD

**Issue by learner4life** [emsec/ChameleonMini#141]
I am using Windows 7 pro 64 Bit. Recently got Chameleon mini from 

https://www.aliexpress.com/item/Newest-13-56MHZ-ISO14443A-Chameleon-Mini-RDV2-0-Kits-RFID-Copier-Duplicator-UID13-56MHZ-NFC-Card/32820382051.html?spm=a2g0s.9042311.0.0.AKT7xs

I was able to install driver and now device is getting reflected on Com port as chameleon.

However, as i want to upgrade firmware , i get following error with Tera Term

200:UNKNOWN COMMAND

When i try to use firmware upgrade.bat, i am getting error 

There was an error with executing this command. Maybe your ChameleonMini is not in bootloader mode?

Please note that all required files are in same folder.

How do i resolve this?

![0a](https://user-images.githubusercontent.com/32249026/30861016-6f2ba1e4-a2da-11e7-80da-2a4a14883698.jpg)
![b](https://user-images.githubusercontent.com/32249026/30861041-8db5d990-a2da-11e7-8728-234911f8b041.jpg)
![c](https://user-images.githubusercontent.com/32249026/30861040-8db431e4-a2da-11e7-8ed7-cfa865d1884d.jpg)
![d](https://user-images.githubusercontent.com/32249026/30861042-8dd5f608-a2da-11e7-8476-e2e1d1be774c.jpg)

Also, i have noticed chipset on device is ATXMEGA 32A4U AU 1449 and not atxmega128a4u

**Comment by geo-rg** [comment]
Since the hardware seems to be completely different from our original hardware, we can give no support in this case. Please contact the manufacturer of the product you have bought.
