### ISSUE TITLE
Any update regarding mifare desfireEv1 support?

### ISSUE THREAD

**Issue by vagha** [emsec/ChameleonMini#145]

**Comment by geo-rg** [comment]
There is the fork <https://github.com/dev-zzo/ChameleonMini/tree/desfire>, which covers a part of DESFire EV1, maybe the functionality you need is already there?

**Comment by dev-zzo** [comment]
@vagha Please check the fork and open issues there; any help with those marked with "help needed" will be greatly appreciated.

**Comment by hamsik7** [comment]
@geo-rg  I have an issue, how to clone/dump Mifare DesFire ev1 any hints will help me alot
![walrus](https://user-images.githubusercontent.com/34604835/34727199-1d4444aa-f54e-11e7-8653-cc7402444ab5.png)

**Comment by dev-zzo** [comment]
@hamsik7 Please use e.g. proxmark3 for that. You will need the card keys anyway, there is no way to dump anything without those. In any case, it is irrelevant to Chameleon.

**Comment by hamsik7** [comment]
@dev-zzo is there any alternative to proxmark3 ? maybe a tool ? i found Mfcuk but i dont think its relevant !
