### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by kaliginium** [emsec/ChameleonMini#146]
Hi,

can you help me with compilation? I still get error:
error: cannot access device-specs for 'atxmega128a4u' expected at 'device-specs/specs-atxmega128a4u'

thank you

**Comment by geo-rg** [comment]
Hi @kaliginium 
Which OS and compiler are you using? It seems like your toolchain is configured wrong.

**Comment by kaliginium** [comment]
I am using Windows 10 OS. Maybe toolchain is configured wrong as you say. I am trying to compile code in cygwin environment,

**Comment by kaliginium** [comment]
Latest I get error:

as: unrecognized option `-mmcu=avrxmega7'
In file included from Chameleon-Mini.h:7:0,
                 from Chameleon-Mini.c:1:
./avr/power.h:1149:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 __power_all_enable()
 ^
./avr/power.h:1198:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 __power_all_disable()
 ^
Chameleon-Mini.c:37:1: fatal error: error writing to -: Invalid argument
 }
 ^
compilation terminated.
make: *** [../LUFA/Build/lufa_build.mk:295: Bin/Chameleon-Mini.o] Chyba 1

**Comment by kaliginium** [comment]
Solved. Just toolchain configuration. Sorry for abuse.

**Comment by geo-rg** [comment]
Glad you could solve it yourself, no need for excuses :)
