### ISSUE TITLE
Possibility to generate masked UID only in middle random?

### ISSUE THREAD

**Issue by gtpy** [emsec/ChameleonMini#153]
Is it possible to generate for BUTTON_ACTION like UID_RANDOM
a functionality to generate a masked UID where only the middle is random?

Example UID for mf_classic_4k_7b (**04**_096E023F_**2280**):
begins only with "04"
ends every time with "2280"

same functionality that it begins with 04 and ends every time with 2480 - middle is random.

I am a really beginner in c - will be great if someone has an idea how this could be possible.

**Comment by geo-rg** [comment]
This is possible, i suggest you have a look in `Button.c`. Right after `case BUTTON_ACTION_UID_RANDOM:` you can find a for loop that starts from 0 and goes up to UidSize. Right before the loop you will need to call `ApplicationGetUid` to obtain the currently set UID and you need to let the loop run from 1 to <UidSize-2. That should do it.

**Comment by gtpy** [comment]
Thanks @geo-rg 

But for my better understandig:

`case BUTTON_ACTION_UID_RANDOM:`
`    {`
`        ApplicationGetUid(UidBuffer);`
`        for (uint8_t i=1; i<ActiveConfiguration.UidSize-2; i++) {`
`            UidBuffer[i] = RandomGetByte();`
`        }`

`        ApplicationSetUid(UidBuffer);`
`break;`

Would this be the right way?

Thanls a lot.

**Comment by gtpy** [comment]
Thanks. Tried it out.
Works well. Thanks @geo-rg

**Comment by herrmanns** [comment]
can anybody send me the chameleon firmware with this "button" option. please i am somehow not able to get this to work.

**Comment by gtpy** [comment]
For The masked uid I can send you the fw. Or I can assist you how to change the code. At Wednesday I am back from holiday

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 27. Jan. 2019, 13:49, herrmanns schrieb:

**Comment by herrmanns** [comment]
that sounds great gtpy. shall we use some email account or irc or anything (i dont have any social media things like fb, instagram etc).
i dont want to spam github. btw i am from GER, too.

**Comment by gtpy** [comment]
@herrmanns How can I contact you?

**Comment by gtpy** [comment]
You got a mail ;)
