### ISSUE TITLE
Open Pull Requests - no merge timeline

### ISSUE THREAD

**Issue by rafb0y** [emsec/ChameleonMini#161]
Hi, I just supported your project and bought a ChameleonMini Rev.G.
Since I am more interested in the rfid communication protocol than in software development, i realized that a lot of missing features have already been implemented by the community but not merged yet.
I would be interested in a compiled hex file :-).
Could you give us a timeline?
Thank you.

**Comment by geo-rg** [comment]
First of all, we appreciate all the contributions! The main problem is that many things are not tested and the main branch shall contain tested code. Also, there are pull requests that are not yet finished, such as the ISO 15693 codec.

Which functionality do you desire in particular?

**Comment by rafb0y** [comment]
https://github.com/emsec/ChameleonMini/pull/118

**Comment by geo-rg** [comment]
Just merged it, but it is not yet tested and the compiled "Latest" version is not yet updated. It would be great if you could check out the repo, compile the code and test if everything works fine.

**Comment by geo-rg** [comment]
@rafb0y I also updated the "latest" precompiled version right now.
