### ISSUE TITLE
info for the wiki

### ISSUE THREAD

**Issue by iceman1001** [emsec/ChameleonMini#167]
Just wanted to give some info for your wiki.
GUI opensourced, in winforms,  works both RevE rebooted and RevG.
https://github.com/iceman1001/ChameleonMini-rebootedGUI

available as click-once deployment if you can't compile the source.

**Comment by iceman1001** [comment]
And there is a GO implementation of GUI,  by @wolfgangmau
https://github.com/WolfgangMau/chamgo-qt

**Comment by geo-rg** [comment]
Thanks for your contributions @iceman1001 @WolfgangMau! I added them to the wiki.
