### ISSUE TITLE
Does it support emulating NFC credit cards?

### ISSUE THREAD

**Issue by NicksonYap** [emsec/ChameleonMini#169]
could'nt find any mentions of credit cards

**Comment by geo-rg** [comment]
Hi @NicksonYap,
this depends on what you want to do with credit cards. If you want to emulate, then no, this is not supported. But basic communication (as reader) should work. If you know about the protocols, you could also use the Chameleon as reader and implement a python script to communicate with the credit card.

Does this answer your question?

**Comment by NicksonYap** [comment]
Hi @geo-rg 
That answers the question.
Sorry for being vague, I meant to emulate credit cards.
It seems that's not supported,but, Thanks!
