### ISSUE TITLE
Why can't I change the setting number? 

### ISSUE THREAD

**Issue by zhujiu** [emsec/ChameleonMini#171]
Hi, Thanks for your open technology, I'm very appreciate your generosity.
Nowdays ,I solder the pcb by myself. And yes it works with reading and emulating.
But  I found a problem, the partlist of device has a fatal mistake, 
BSS84AKW should change to    BSS84PW
BSS138BKW should change to  BSS138PW
and if you do  not change the part number, you can not read the uid number.

And here is my question,hahaha..
when I try to change the setting from 1 to other numbers,  it can't works,it still in 1 setting.
and there was  a  detail thing  I noticed，when I changed the settings, the COM Tera Term VT will disconnect form the chameleon and then connect it again.
So, I was stuck in here , please help me .And if anyone want to connect me in other detail things about chameleon  ,please send emial to me:  809687990@qq.com or Wechat number:  zhujiu00

**Comment by zhujiu** [comment]
@doegox @robots @cons0l3 @0x715C @uhei

**Comment by AndreasBujok** [comment]
I'm alitzle nur confused. Solder by yourself?
I know only about complete cards.

Cheers

**Comment by zhujiu** [comment]
@AndreasBujok yes, i solder it by myself.
And does your chameleon could change the setting  for 1 to 2 ,  
like this command ;  setting =2
when i  set this command , and then check setting , the setting is still equal to 1. 
I do't know why?please help me .

**Comment by zhujiu** [comment]
@AndreasBujok @doegox @robots @cons0l3 @0x715C

**Comment by geo-rg** [comment]
Hi @zhujiu 
first of all: congrats for accomplishing to solder the Chameleon by yourself, we know that this is not very easy!
I suppose you use an ATxmega128a4u and that you are using a standard firmware here from the GitHub project. If not so, these are probable causes.
For changing the setting, it is necessary to access the eeprom, so you may also check whether you have any problems accessing the eeprom.

**Comment by zhujiu** [comment]
@geo-rg actually  Im a hardware engineer， so  it's not so hard for me。 
yep， i'm not very famili with codeing。  and thanks for  your advice， i will chek  the eeprom 。

**Comment by zhujiu** [comment]
@geo-rg  Could you tell the correct part number of the eeprom?
Does the device's name is MB85Rs256?  256KB flash?

**Comment by zhujiu** [comment]
@AndreasBujok @geo-rg @doegox @robots @cons0l3

**Comment by Peterthegreat** [comment]
> But I found a problem, the partlist of device has a fatal mistake,
> BSS84AKW should change to BSS84PW
> BSS138BKW should change to BSS138PW
> and if you do not change the part number, you can not read the uid number.
More information or reasons why? I am facing a similar issue but autocalibrate dose the trick.

**Comment by zhujiu** [comment]
@Peterthegreat   contact me with my email 809687990@qq.com

**Comment by Peterthegreat** [comment]
> @Peterthegreat contact me with my email 809687990@qq.com
@zhujiu No reply from that email address, but took the chance and gave it a try. Thank you so much! Now the read UID works. Will now test my other issues with the Chameleon

**Comment by geo-rg** [comment]
I guess the problem is solved now. Please re-open this issue if not.
