### ISSUE TITLE
Unable to IDENTIFY Mifare Classic 7 byte UID tags

### ISSUE THREAD

**Issue by karlkr** [emsec/ChameleonMini#176]
I am using latest RevG firmware:
_ChameleonMini RevG 180228 using LUFA 151115 compiled with AVR-GCC 5.4.0. Based on the open-source NFC tool ChameleonMini. https://github.com/emsec/ChameleonMini commit 7ab8d3b_

and I am unable to correctly IDENTIFY Mifare Classic 7 byte UID cards.

Currently I have this response
```
IDENTIFY
101:OK WITH TEXT
Unknown card type.
ATQA:	4400
UID:	04XXXXXXXXXX80
SAK:	08
```
Proxmark hf search gives the following on the same card
```
UID : 04 XX XX XX XX XX 80           
ATQA : 00 44          
SAK : 08 [2]          
TYPE : NXP MIFARE CLASSIC 1k | Plus 2k SL1          
MANUFACTURER : NXP Semiconductors Germany    
```
This _unknown card type_ response also cancels the CLONE procedure on these cards. Is this a problem of my card or a bug? Thanks in advance.

**Comment by geo-rg** [comment]
The firmware expects Mifare Classic cards to have 0400 as ATQA and thus does not recognize 7-byte MFC cards (which seem to have 4400 as ATQA). You could simply add a line [here](https://github.com/emsec/ChameleonMini/blob/master/Firmware/Chameleon-Mini/Application/Reader14443A.c#L90) to fix this problem. Feel free to hand in a patch!
