### ISSUE TITLE
Sniffer 

### ISSUE THREAD

**Issue by nurzhannn** [emsec/ChameleonMini#186]
Hello
how to remove the restriction  SNIFFER CARD -->READER  and intercept all data with command CONFIG=ISO14443a_SNIFF ?

**Comment by gypsophlia** [comment]
Please upgrade to the latest firmware

**Comment by nurzhannn** [comment]
> Please upgrade to the latest firmware

i have "reve-2" it stands there atxmega32a4u,will the new firmware work?

**Comment by geo-rg** [comment]
@nurzhannn Sorry but no, the sniffing firmware is only for RevG.

**Comment by nurzhannn** [comment]
this restriction is specially done?

**Comment by nurzhannn** [comment]
i bought for the sake of the sniffing,what should i do with him ?

**Comment by nurzhannn** [comment]
American capitalists :)

**Comment by ceres-c** [comment]
The code is here available, you are free to backport it into the other repo. Easy, innit? ;-)
Or you can buy the revg which is already supported by new code and will be supported in the future...

**Comment by nurzhannn** [comment]
after firmware Revg need to calibrate, yes ? :-)

**Comment by geo-rg** [comment]
Hi @nurzhannn 
if you do not have a RevG Chameleon by Kasper & Oswald, I cannot help you here. Earlier in this thread you stated that you have a RevE (rebooted?) chameleon.

If you have a RevG by Kasper & Oswald, you may re-open this issue. Else, please contact the manufacturer of your Chameleon.
