### ISSUE TITLE
How to read the logs

### ISSUE THREAD

**Issue by sp4rrows** [emsec/ChameleonMini#190]
Hello everybody,
I'm new to nfc.
Does anyone have a reading to learn general and how the logs f.e from chameleon are read / interpreted?
I'm playing around with my new chameleon but need some point to start.

Thanks a lot.

**Comment by geo-rg** [comment]
The log can be downloaded from the Chameleon either with a terminal emulator and the Chameleon command `logdownload` or with the [chamlog tool](https://github.com/emsec/ChameleonMini/tree/master/Software).

**Comment by sp4rrows** [comment]
@geo-rg  thanks that worked. 
Is there any hint, book, documentation how I can learn more about these logs in general.
I’m not so familar in rfid. Need to learn it on my own.(Also I am a beginner in programming)
Example: 
How to read them / understand them?
Thank you.

**Comment by maxieds** [comment]
If you are looking for a user friendly GUI on an Android phone, you can
check out my app: https://github.com/maxieds/ChameleonMiniLiveDebugger

**Comment by sp4rrows** [comment]
Thanks. I’ll go on search and try it out.

**Comment by gtpy** [comment]
For understanding the chameleon it is good to read the 
https://rawgit.com/emsec/ChameleonMini/master/Doc/Doxygen/html/_page__getting_started.html
Then try out and use command line to understand it better.
Then you could use the GUI and Android tool which is a great help.

**Comment by AndreasBujok** [comment]
That's also my stand on the beginning - i was total confused. I'm not familiar with the kind of doxygen docu.

After growing of the "HowTo" i've written an own docu: https://github.com/AndreasBujok/ChameleonMini

Could be helpful for your request :-)

BR Andreas
