### ISSUE TITLE
Rawgit is sunsetting - change cdn links

### ISSUE THREAD

**Issue by jacebenson** [emsec/ChameleonMini#192]
I noticed you linked to rawgit.  
rawgit is sunsetting October of 2019 so I suggest you change your hosting links to some other CDN.

https://www.jsdelivr.com/rawgit
https://www.rawgit.com/

![image](https://user-images.githubusercontent.com/638764/49250093-9b188000-f3e3-11e8-80da-de5daceae9f3.png)

**Comment by geo-rg** [comment]
Thanks for the hint, we'll change it soon!
