### ISSUE TITLE
Communication problem with chameleon

### ISSUE THREAD

**Issue by viertel** [emsec/ChameleonMini#199]
Hello Together,

I have flashed the chameleon with respect to this tutorial: https://rawgit.com/emsec/ChameleonMini/master/Doc/Doxygen/html/_page__getting_started.html
Everything seems to work fine. The Chameleon is found into the DeviceManager as "Serial USB-Device (COM7). Then I used TeraTerm to connect to the Chameleon but always the error: "Cannot open COM7 (0x00000079" occurs. 

My os is Windows 10 (64bit).

I tried different settings:
Different USB ports, changed the power button from on to off etc. 

I have no further ideas why it dont work. Please help me.

Best regards, 
viertel

**Comment by geo-rg** [comment]
Have you installed the drivers as stated in the [getting started](https://rawgit.com/emsec/ChameleonMini/master/Doc/Doxygen/html/_page__getting_started.html)?

**Comment by viertel** [comment]
Hello, thank you for your reply.
Yes I have right clicked the "atmel_usb_dfu.inf" file and clicked install. The Installation was acknowledged successfully. 

Greeetings
viertel

**Comment by geo-rg** [comment]
Hi @viertel 
I am usually not working with Windows but I think the Chameleon should show up as Chameleon Mini in the device manager and not as "Serial USB-Device". Can someone who uses Windows confirm this?

**Comment by herrmanns** [comment]
Yes that is correct. It should show something like ChameleonMini Virtual Serial Port (COMX)

**Comment by jan1702** [comment]
Hi,
I have a problem with the chameleon mini rev G. 
![unbenannt](https://user-images.githubusercontent.com/46749394/51250782-cfe29580-1997-11e9-91e1-3526e5a14f0a.jpg).

What can i do to fix this?
I tried to upload new firmware 3 times.
May someone has an idea.
Thanks

**Comment by geo-rg** [comment]
Hi @jan1702, I opened a new issue #202 for you, since your problem does not refer to this issue.

**Comment by viertel** [comment]
Hello toghter,  okay thank you for your feedback. I tried to install the driver multiple times, but in the windows device manager of windows i didn't get something like ChameleonMini Virtual Serial Port (COMX). Any other ideas? Maybe i will try it on linux.
Greetings Fabien

**Comment by herrmanns** [comment]
Have you possibly some driver signing issue? (i am not sure if it was proxmark3 or chameleon).
Just in case ... you can try to switch off driver signing. there are several ways to do it but IMHO the "advanced boot version" is the best one to choose.
https://www.howtogeek.com/167723/how-to-disable-driver-signature-verification-on-64-bit-windows-8.1-so-that-you-can-install-unsigned-drivers/
it is only an idea. 
I guess you already tried the manual installation of a driver. not automatic.  check this video from minute 1:50
https://www.youtube.com/watch?v=S97hJsg4H20

**Comment by geo-rg** [comment]
Hi @viertel 
I assume you found a solution. If not so, please re-open this issue and provide further information.
