### ISSUE TITLE
Problem setting config to vicinity

### ISSUE THREAD

**Issue by geo-rg** [emsec/ChameleonMini#202]
Hi,
I have a problem with the chameleon mini rev G. 
![unbenannt](https://user-images.githubusercontent.com/46749394/51250782-cfe29580-1997-11e9-91e1-3526e5a14f0a.jpg).

What can i do to fix this?
I tried to upload new firmware 3 times.
May someone has an idea.
Thanks

_Originally posted by @jan1702 in https://github.com/emsec/ChameleonMini/issues/199#issuecomment-454772263_

**Comment by geo-rg** [comment]
@jan1702 In order to check which configurations are available, you can type `config=?`. As you will find out, VICINITY is not an option, since this is not yet supported by the firmware. However, this will be soon available and if you want to try it out already, you can have a look here: #182 

You can check out this pull request and compile this firmware by yourself to try the vicinity config.

**Comment by ceres-c** [comment]
You can use my repo, but notice Vicinity hasn't been actually implemented, it's mostly a stub
The easiest tag you can find is Titagitstandard, while EM4233 has more complete and better engineered code
