### ISSUE TITLE
Switch button stopped working 

### ISSUE THREAD

**Issue by dealaddict** [emsec/ChameleonMini#205]
My switch button is not working and it is not able to switch cards. This only happens on battery mode. While it is connected to the computer, the switch and lights work, but once disconnected from usb the button no longer works. I can't switch between tags. 

Appreciate your help.

**Comment by gtpy** [comment]
https://github.com/iceman1001/ChameleonMini-rebooted/issues/65

It sounds that’s a RevE Rebooted device?

Maybe other users of the "RevE rebooted" could tell if it is a normal behavior. I can only guess because I don't own a rebooted device.

**Comment by gtpy** [comment]
It looks solved (rebooted device). Pls close issue.
