### ISSUE TITLE
How to make bin file for Chameleon Mini? 

### ISSUE THREAD

**Issue by dealaddict** [emsec/ChameleonMini#206]
I need to convert my Mifare Ultralight++ dump files which are in a txt format to bin format.

I have windows and android.

**Comment by geo-rg** [comment]
Hi @dealaddict 
you can use the [Windows version of xxd](http://www.wzw.tum.de/public-html/syring/win32/UnxUtilsDist.html) for that.

**Comment by dealaddict** [comment]
@geo-rg 

Hi. I ran the app but not sure what commands to type. There's only one app inside called SH.exe
 I tried typing this `xxd -r -p 1502.txt 1502.bin` but it didnt do anything. I am pretty stupid and noob so forgive me on these commands.
