### ISSUE TITLE
New Chameleon setup

### ISSUE THREAD

**Issue by ph553** [emsec/ChameleonMini#207]
Hi
I just received my chameleon rev G and i flashed the firmware as instructed. I am using iceman's GUI and this is the main screen i get:
![image](https://user-images.githubusercontent.com/27577796/53254822-3727ef80-3692-11e9-9c8d-3db207887e92.png)

**Comment by ph553** [comment]
Nevermind, i tried using the serial interface and it's working.

**Comment by gtpy** [comment]
Maybe try https://gitlab.com/Gtpy/ChameleonMini-RevG_GUI

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 22. Feb. 2019, 17:09, ph553 schrieb:

**Comment by ph553** [comment]
Thanks, i'll try it :)

**Comment by gtpy** [comment]
But I wonder why the iceman gui not work. I test it a few weeks ago and it worked. I'll try it out again later today.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 22. Feb. 2019, 17:42, ph553 schrieb:

**Comment by ph553** [comment]
Does the iceman program have a cache? i used to have a rev E rebooted and it might be because the program thinks it's still a rev E?
