### ISSUE TITLE
masterkey / reader attack can somebody help me out!

### ISSUE THREAD

**Issue by yaxax** [emsec/ChameleonMini#212]
I can not get out with the proxmark3.I try to make a master key but I can not. I also try to get info from the reader  but I can not. I am new in this I am learning can someone helping me with that and explained me how

**Comment by geo-rg** [comment]
Hi @yaxax 
generally, we cannot give explanations about attacks. I assume you are talking about attacking Mifare Classic. You could start with reading [the academic papers](https://scholar.google.de/scholar?q=mifare+classic) about this topic, read related issues ([1](https://github.com/emsec/ChameleonMini/issues/203), [2](https://github.com/emsec/ChameleonMini/issues/111), [3](https://github.com/emsec/ChameleonMini/issues/110)), look at the documentation ([1](https://github.com/Proxmark/proxmark3/blob/master/tools/mfkey/mfkey32.c#L21-L22), [2](https://github.com/Proxmark/proxmark3/blob/master/tools/mfkey/mfkey64.c#L23)) or have a look into the [proxmark's repository issues page](https://github.com/Proxmark/proxmark3/issues).

Please do **not** re-open this issue to ask more about attack descriptions. If you have problems with using the Chameleon, feel free to open a new issue.
