### ISSUE TITLE
Is sniffing Reader Communication possible?

### ISSUE THREAD

**Issue by eXspir3** [emsec/ChameleonMini#216]
Hi,

Is it possible to use the ChameleonMini REV G for sniffing what keys a reader tries on a specific tag?

Best Regards

**Comment by geo-rg** [comment]
Hi @eXspir3 
first of all: Generally, we do not give hints on attacks here. If your question refers to Mifare Classic, please have a look at [this](https://github.com/emsec/ChameleonMini/issues/212#issuecomment-469163911) comment.

If you refer to cards using AES or 3DES encryption for authentication, most probably you cannot recover the key by sniffing. 

If you have any further questions regarding a Chameleon-related topic (NOT about an attack), please open a new issue.
