### ISSUE TITLE
Installing the driver on Windows 7?

### ISSUE THREAD

**Issue by Xykon** [emsec/ChameleonMini#22]
Hello,

I got the ChameleonMini today and tried it on my Notebook which is running Windows 7.

When I connect it via MicroUSB the device manager finds LUFA CDC demo with an exclamation mark. So I downloaded a zip file of the project, went to the driver folder and right-click on the ChameleonDriver.inf file. But all I get is a message that the inf file I selected does not support this method of installation.

EDIT: I now did manage to install the DFU driver manually and upgrade but I still can't install the LUFA CDC Demo driver.

I tried to install the driver for LUFA CDC demo but I get an error that "Windows can't verify the publisher of this driver software."

I looked through the documentation but the getting started guide doesn't seem to mention anything about how to install the drivers to get started.

**Comment by r4b3** [comment]
No need for a LUFA driver.
All you need is described here
https://rawgit.com/emsec/ChameleonMini/master/Doc/Doxygen/html/Page_GettingStarted.html

Download the
- dfu Programer,
- The. bat File
- .eep and hex file
-. inf and cat file for the Chameleon

**Comment by Xykon** [comment]
I did all what is described on that page and I did manage to update. I also have the .inf and .cat files but they don't install saying "Windows can't verify the publisher of this driver software."

**Comment by r4b3** [comment]
u can disable the check for driver signing
http://ccm.net/faq/3914-how-to-install-unsigned-drivers-on-windows-7
this should help

**Comment by Xykon** [comment]
I tried this but it seems our IT department disabled this. Looks like I have to get another computer to try this thing.
