### ISSUE TITLE
chamlog.py error 

### ISSUE THREAD

**Issue by sp4rrows** [emsec/ChameleonMini#222]
Hi,
When I open a logfile I get the following error:

`python chamlog.py -f log_cham_rec_mix `

`Note: If parityBit check failed, '!' is appended to the decoded data and raw data with parity bit is displayed.`

`Traceback (most recent call last):`
 ` File "chamlog.py", line 108, in <module>`
   ` main()`
  `File "chamlog.py", line 101, in main`
  `  log = Chameleon.Log.parseBinary(handle, args.decode)`
 ` File "/home/Software/Chameleon/Log.py", line 130, in parseBinary`
   ` logData = eventTypes[event]['decoder'](logData)`
 ` File "/home/Software/Chameleon/Log.py", line 51, in binaryParityDecoder`
    `isValid, checkedData = checkParityBit(data)`
 ` File "/home/Software/Chameleon/Log.py", line 23, in checkParityBit`
    `bit = (data[byteIndex] >> bitIndex) & 0x01`
`TypeError: string indices must be integers, not float`

Some other logfiles work well. 
Has anyone got an idea what went wrong, or an approach where I can search further?
Or the logfile may be corrupted?

Thanks.

**Comment by geo-rg** [comment]
Hi @sp4rrows 
it seems like you are using python*2*, please use python*3*. The code uses math.floor, which returns a float in python2, but an int in python3.
