### ISSUE TITLE
Sniff problem TX

### ISSUE THREAD

**Issue by sp4rrows** [emsec/ChameleonMini#223]
Hi,
I am trying to sniff both way.

Setting1: `config=mf_classic_1k`
Setting2: `config=iso14443a_sniff`
Setting3: `config=iso14443a_reader`
`Logmode=memory`

Reader was autocalibrated with 1k card.

Tested with different Readers:
- Smartphone (NXP TagInfo, NFC Tools Pro)
- ACR122U

Logfile only show RX and no TX

**<details><summary>LOG</summary>**
<p>

`python chamlog.py -f logfile`

`Note: If parityBit check failed, '!' is appended to the decoded data and raw data with parity bit is displayed.`

`00000 ms <    +0 ms>:BOOT                         (0   bytes) [                    ]    `
`12749 ms <+12749 ms>:CODEC RX SNI READER          (1   bytes) [26                  ]    `
`12766 ms <   +17 ms>:CODEC RX SNI READER          (2   bytes) [9320                ]    `
`12773 ms <    +7 ms>:CODEC RX SNI READER          (9   bytes) [93702d6332493516bd  ]    `
`12779 ms <    +6 ms>:CODEC RX SNI READER          (4   bytes) [500057cd            ]    `
`14677 ms < +1898 ms>:CODEC RX SNI READER          (1   bytes) [26                  ]    `
`14695 ms <   +18 ms>:CODEC RX SNI READER          (2   bytes) [9320                ]    `
`14702 ms <    +7 ms>:CODEC RX SNI READER          (9   bytes) [93702d6332493516bd  ]    `
`14708 ms <    +6 ms>:CODEC RX SNI READER          (4   bytes) [500057cd            ]   ` 
`16336 ms < +1628 ms>:CODEC RX SNI READER          (1   bytes) [26                  ]    `
`16354 ms <   +18 ms>:CODEC RX SNI READER          (2   bytes) [9320                ]    `
`16361 ms <    +7 ms>:CODEC RX SNI READER          (9   bytes) [93702d6332493516bd  ]    `
`16367 ms <    +6 ms>:CODEC RX SNI READER          (4   bytes) [500057cd            ]    `
`17666 ms < +1299 ms>:CODEC RX SNI READER          (1   bytes) [26                  ]    `
`17683 ms <   +17 ms>:CODEC RX SNI READER          (2   bytes) [9320                ]    `
`17691 ms <    +8 ms>:CODEC RX SNI READER          (9   bytes) [93702d6332493516bd  ]   ` 
`17697 ms <    +6 ms>:CODEC RX SNI READER          (4   bytes) [500057cd            ]    `
`00000 ms <+47839 ms>:BOOT                         (0   bytes) [                    ]    `

</p>
</details>

Has anyone another Idea what I am doing wrong or what is missing?
See #220 but nothing worked 

Thanks for every hint.

**Comment by fptrs** [comment]
Solved in #220
