### ISSUE TITLE
chameleon mini reve-2

### ISSUE THREAD

**Issue by nick500** [emsec/ChameleonMini#242]
Can I upload firmware Chameleon Mini RDV2.0 ?

**Comment by ceres-c** [comment]
Excuse me, what?
What is ChameleonMini RDV2.0? Are you referring to [ChameleonMini Rev.E Rebooted](https://github.com/iceman1001/ChameleonMini-rebooted)?

**Comment by nick500** [comment]
> Простите, что?
> Что такое ChameleonMini RDV2.0? Вы имеете в виду [перезагрузку ChameleonMini Rev.E](https://github.com/iceman1001/ChameleonMini-rebooted) ?

Yes. My chameleon https://store.ryscc.com/blogs/news/34542273-unleash-the-chameleons            can i make him a sniffer or Chameleon Mini RDV2.0?

**Comment by ceres-c** [comment]
If your chameleon uses the ATxMega32A4U MCU you should go [here](https://github.com/iceman1001/ChameleonMini-rebooted).
That repository has different features to this one
