### ISSUE TITLE
Support for EM4100

### ISSUE THREAD

**Issue by Thor77** [emsec/ChameleonMini#250]
Are there any plans to support EM4100 chips?
Is the hardware even capable of reading/emulating those?
I would like to read/emulate [this](http://www.stronglink-rfid.com/en/rfid-cards/tk4100.html) card (this page states the protocol as ISO10536 / EM4100 compatible).

**Comment by Endres** [comment]
Unfortunately this will never be possible with the current hardware, as EM4100 is running with 125 kHz RF frequency, whilst NFC and other widely used tags operate at 13.56 MHz, so the ChameleonMini is designed to work with 13.56 MHz. In theory, it would be possible to emulate 125 kHz tags, however you would need hardware supporting this lower frequency (LF) RFID.
