### ISSUE TITLE
Chameleon working in windows but not linux

### ISSUE THREAD

**Issue by ArthurPons** [emsec/ChameleonMini#258]
Hello all,

I connected to my Chameleon on Linux with the command `socat - /dev/ttyACM0,crnl`, tested the `VERSION?` command which worked fine. Ientered the bootloader, I executed the exact same command as in the "Getting started" wiki page with success.

After that, when I execute `socat - /dev/chameleon,crnl` and any Chameleon command I get no answer at all.
However if I use TeraTerm in Windows I get responses and the Chameleon apparently works fine.

I'm having a hard time understanding why I got feedback with the test firmware but none with the proper one in Linux. I guess it's because the commands aren't actually sent to the device but I have very little prior knowledge to troubleshoot any of it.

**Comment by fptrs** [comment]
Hi @ArthurPons,
did you read #64?
