### ISSUE TITLE
BOM correction (for selfmade hw)

### ISSUE THREAD

**Issue by robots** [emsec/ChameleonMini#260]
Hi,
for all of you guys who made Chameleon Mini on their own here is little advice:

Capacitors C29 and C30 should be 47pF.

This tunes the mismatch between transmitter and antenna. It increases reader distance from -1 to about 2-3cm. RSSI without tag changes from 500-600 to ~2500mV.

More about this here: https://my.eng.utah.edu/~mlewis/ref/NFC/AN1445.pdf

**Comment by timokasper** [comment]
Hi robots, Thanks for the advice, but I cannot recommend to follow your advice. The RSSI without tag, with exactly the components of the BOM, should be more than 10V - all of the ChameleonMini RevG sold in the webshop of Kasper&Oswald have to pass this test! It seems that you have made some other mistake during manufacture. I have spent about a week for fine-tuning the antenna matching both for emulation and reader operation of Rev.G, before we had several thousand devices produced after the kickstarter project...  and changing the value of a single (or even 2) capacitors affected all capabilities (sniffing, reading, emulating, ...) it was a tidious try-and-improve approach and I think we have found a good compromise for the tuning....     anyway, 2500mV is definitely not enough, there is s.th. wring with your device.

**Comment by robots** [comment]
Well, its been 2years since i made the board. I dont remember what parts were ordered, but it could be problem on my side :-) I will replace all RF frontend parts just to be sure.

**Comment by libin-ka** [comment]
What is the capacitance value of C29 C30

**Comment by robots** [comment]
these capacitors are not populated in BOM

**Comment by libin-ka** [comment]
![5047](https://user-images.githubusercontent.com/46210417/80964782-0d488c00-8e44-11ea-800a-34f39c2c6941.jpg)

**Comment by libin-ka** [comment]
> 这些电容器未填充在BOM中
See pictures c29 and c30 in the wiki
https://github.com/emsec/ChameleonMini/wiki
