### ISSUE TITLE
Can it be used to emulate contactless bank card?

### ISSUE THREAD

**Issue by leadrig** [emsec/ChameleonMini#261]

**Comment by ceres-c** [comment]
ISO14443-A codec is currently implemented in the codebase, but EMV contacltess uses both -A and -B standards, so the lack of the second one could be an issue. Also, there is no way the crypto operations can be performed on the ATMega fast enough. And you'd need the private key.
https://www.cs.ru.nl/E.Poll/papers/EMVtechreport.pdf

So, it's a no.
