### ISSUE TITLE
Legic prime/advant

### ISSUE THREAD

**Issue by siegesa1** [emsec/ChameleonMini#267]
Hi 

Assuming having a working  Legic dump from Proxmark.
Is there a way to load it to an Chameleon RevE and simulate this dumped Legic Card, like on Proxmark3?

Cheers
voya

**Comment by david-oswald** [comment]
Duplicate of #234 

In principle the hardware could emulate legic prime, but that would require writing a) the codec and b) the application.

**Comment by siegesa1** [comment]
Hi Dave

Thx for the replay, that was what I assumed.
So I stick at the version, to simulate it via Proxmark...
