### ISSUE TITLE
emulate function problem！

### ISSUE THREAD

**Issue by KiraCheng6** [emsec/ChameleonMini#295]
i am using the tiny pro(same as the mini revg),i have already upgrade the revg firmware but still having problem.

the situation is:
 i already have a dump and i upload both app and GUI, the dump have change, and i have no idea

the PIC is showing the situation,the left side is the dump i download back from the tiny pro, the right side is the dump i actually upload,

thanks for help!

<img width="1294" alt="iShot2021-03-02 18 03 38" src="https://user-images.githubusercontent.com/25243464/109632149-b0ac1f80-7b81-11eb-8c0f-3b4526f114d1.png">

**Comment by KiraCheng6** [comment]
<img width="1294" alt="iShot2021-03-02 18 03 38" src="https://user-images.githubusercontent.com/25243464/109632091-a25e0380-7b81-11eb-8c11-b168da05a191.png">

**Comment by david-oswald** [comment]
Please contact the manufacturer of the Tiny Pro - this repo only supports the original RevG
