### ISSUE TITLE
Cannot refresh dump once it has been downloaded (App)

### ISSUE THREAD

**Issue by rsurgiewicz** [emsec/ChameleonMini#299]
Hi,

I don't know if I'm doing something wrong but steps to reproduce:

Using app
1. Clone a card e.g Mifare Ultralight
2. Download dump
3. Modify content
4. Upload dump
5. Download dump for verification --> modification is "present"
6. Clone same card again 
7. Download the dump --> **still dump is a "modified" one, but should be cloned from source card** //expected to see source card data read
8. Close app/ change card type/ refresh etc
9. Close same card again
10. Download the dump --> **still dump is a "modified" one, but should be cloned from source card** //expected to see source card data read

The only way I found to completely "clean it"  is to connect to windows app and "Clear"
Then again in app
Clone same card & download the dump --> finally shows the source card data.

Q: Is it a bug?
Q2: How to re-read the source card content and dump?

**Comment by fptrs** [comment]
Hi @rsurgiewicz,
I suggest you open an issue on the repository of the app you are using. This repo is for the official firmware of the Chameleon-Mini.
If you encounter a problem specific to the Chameleon-Minis firmware I am happy to help.
