### ISSUE TITLE
Problem with Bluetooth and UID write 00000000000

### ISSUE THREAD

**Issue by sejozawer** [emsec/ChameleonMini#309]
Hi. I bought ChameleonMini from Aliexpress 1y ago.
And now I wanted to use him, but I have problem.

(He looks like --> https://prnt.sc/23nz4tn )

He can't write UID.

He doesn't have problem with connect to computer.
He doesn't have problem with DFU.
He doesn't have problem with change all buttons with app.
He doesn't have problem with upgrade.

BUT:
He has problem with Bluetooth connect. App doesn't see ChameleonMini.
I can connect to smartphone only from OTG cable (but it's look like as USB_NUMBER155451 for example). From smartphone I can change settings and buttons, but I CAN'T WRITE UID. 
He can't remember the UID. (UID - write - succesfull - but I have value only 0000000000 )
He can't sniff devices. I hold button for sniff but I don't have result.

Help me please, how I can decide problem with:
1) Bluetooth connection
2) UID write
3) sniff

**Comment by david-oswald** [comment]
Hi, sorry we don't support regarding problems with third-party hardware here, you can however try the RRG discord. What you describe though sounds like a hardware problem, so best to contact the Aliexpress seller you bought from.
