### ISSUE TITLE
Connect device to the LabVIEW

### ISSUE THREAD

**Issue by sina6611** [emsec/ChameleonMini#338]
Hi everyone,

I am trying to control Chameleon mini with commands using a LabVIEW program and a serial USB port. I am sending the commands, but I am not receiving any replies. I have tried the following:

Checking the USB connection
Using the correct COM port number
Checking the commands I am sending
Updating the firmware of the device
I am still not receiving any replies from the device. Has anyone else had this problem? If so, how did you solve it? Any help would be greatly appreciated.

Thanks

**Comment by tomaspre** [comment]
Hello,

Did you try communicating with the device using a serial terminal? Try using TeraTerm, for example.

Also, keep in mind that there is no echo from the Chameleon, which could definitely confuse some programs.

**Comment by tomaspre** [comment]
Closing this, as it's stale.
