### ISSUE TITLE
Set new UID

### ISSUE THREAD

**Issue by sina6611** [emsec/ChameleonMini#341]
Hi everyone,

I want to set a new UID in the Chameleon Mini and I have used the command UID=<UID>. For example, I have set UID=<1234567989ABCDEF>, but the Chameleon Mini answers INVALID parameter. Does anyone know how I can set a new UID on it?

**Comment by spankywetfish** [comment]
You don’t need the `<>`, they are there to indicate that a parameter is required.
E.g. `UID=12345`

**Comment by r1ddl3rz** [comment]
> Hi everyone,
> 
> I want to set a new UID in the Chameleon Mini and I have used the command UID=<UID>. For example, I have set UID=<1234567989ABCDEF>, but the Chameleon Mini answers INVALID parameter. Does anyone know how I can set a new UID on it?

And you need to have a valid length for the UID. 
For example cfg=MF_CLASSIC_1K
Correct: UID=11223344 
Invalid Parameter: UID=1122334455

**Comment by sina6611** [comment]
It works. Thank you
