### ISSUE TITLE
Where are the "Latest" directory of RevG?

### ISSUE THREAD

**Issue by AndreasBujok** [emsec/ChameleonMini#345]
Hi

Sorry, but i wan't update my RevG to the newest precompiles firmware.
But i found only the *.hex and *.eep files for RevE.

In the past there was a directory "ChameleonMini-master\Firmware\Chameleon-Mini\Latest".

I don't want to create the ccomplete winsetup to compile it by my self.

Thanks
Andreas

**Comment by ceres-c** [comment]
You can find it in the [release list](https://github.com/emsec/ChameleonMini/releases)

**Comment by AndreasBujok** [comment]
Oh, thanks a lot

:-)

**Comment by AndreasBujok** [comment]
:-)
