### ISSUE TITLE
ATxmega128a4u Fuse setting? 

### ISSUE THREAD

**Issue by zhansw** [emsec/ChameleonMini#43]
Hi,

I got my Rev.G today,when DFU firmware updated done. 
the windows can't found the device and virtual com port.
an USB cannot recognize message show quickly when device plug in,and LED keeping on green.

then try use my MKII reprogram the bootloader and still no help.
the FUSE setting list by:

0x00
0xFF
0xFE
0xFF

that looks difference of the old Rev.E setting's.
so just confirm the fuse setting is right?

Best Regards and Thanks!

**Comment by feifeilanniao** [comment]
no need to change the fuse setting
