### ISSUE TITLE
chamtool.py fails uploading small files

### ISSUE THREAD

**Issue by doegox** [emsec/ChameleonMini#47]
An Ultralight dump is only 64b but chamtool.py requires at least 128b for the XMODEM packets.
When using another xmodem tool such as minicom, they pad the 64b to 128b and send it successfully.
chamtool.py should do the same to allow sending Ultralight dumps easily.

**Comment by david-oswald** [comment]
Yep will do - as mentioned chamtool is not really fully debugged or stable
