### ISSUE TITLE
Superflous part of PCB

### ISSUE THREAD

**Issue by exander77** [emsec/ChameleonMini#56]
![ac028e1c61cba02de890159371b1e672_original](https://cloud.githubusercontent.com/assets/2256039/19708368/4865b636-9b1e-11e6-89ce-1e3c4247b892.jpg)

What is purpose of this part? Can it be safely removed? Why is that even there?

**Comment by kinoka2k** [comment]
This is actually used for slot based RFID readers that use a switch.  It's designed to trigger the switch in the slot.  It can be broken off if you do not wish to use this feature in the future.  Kasper explains this in his videos.

**Comment by exander77** [comment]
Oh, great to now. Have to check those videos.
