### ISSUE TITLE
Difference between PCB RevE-2 and RevE-3

### ISSUE THREAD

**Issue by zhovner** [emsec/ChameleonMini#6]
Hello. I'm ready to print PCB but little confused. 
In repository I found only RevE-2 board but here http://www.mikrocontroller.net/topic/327629 people talk about RevE-3. 
The main difference is in antenna size and bottom left corner element. 
Can you please explain what version is better to use?

![ChameleonMini pcb reve2 between reve3](http://i.imgur.com/VtscG2d.png)

**Comment by david-oswald** [comment]
Hi, 

RevE-3 is a fork by another Github user (https://github.com/NeoFromMatrix/ChameleonMini), we only provide RevE-2, probably the difference is minor though.

- David
