### ISSUE TITLE
how to calibrate C2 value ?

### ISSUE THREAD

**Issue by Georges760** [emsec/ChameleonMini#7]
i have made a ChameleonMini, successfully installed firmware, and have access to console configuration.

When trying to emulate a card, I found cannot scan it with a reader (phone or ACR121). Maybe it is due to the RF antenna filtering, and specially the C2 value.

Can you advise a way to diagnose this issue ? and a explanation of C2 value over antenna spec ?

Thanks

**Comment by david-oswald** [comment]
Hi,

a few things to check:

Which card type have you selected in the terminal? Did you check the soldering in the RF area? Some components are quite tiny there. You could probe signals (e.g. DEMOD should show some data from the reader, LOADMOD should be driven by the Xmega, SUBCARRIER as well) and check they are OK. Same goes for the field, use a few turns of wire or an RF probe if you have connected to your scope to see if the chameleon load-modulates correctly.

C2 is not crucial to the function, but can improve range. Bringing the antenna to exact resonance is easiest with a VNA. 

You can also remove the circuitry for the passive mode (R5, D2A, D2B, D4A, D4B), some readers don't like it / have minimal range.

Best
David
