### ISSUE TITLE
Chamtool.py didn't work?

### ISSUE THREAD

**Issue by ykpe** [emsec/ChameleonMini#70]
My chamtool.py keep failing as issue#16.
  File "/multimedia/git/ChameleonMini/Software/Chameleon/Device.py", line 134, in writeCmd
    statusCode, statusText = status.split(":")
ValueError: need more than 1 value to unpack

Therefore, I've update firmware to ChameleonMini
But chamtool.py didn't react to -p comport(Mine was COM3)
![fail](https://cloud.githubusercontent.com/assets/6124920/19827948/a67494a2-9deb-11e6-9385-0b6858bd9b47.png)

System:Win 10 64-bit, Python ver 3.5

One more question, 
My dump_mfu always showed timeout when dumping my classic 1K card by using Teraterm
Reading works find for me, though. 

Any suggestion?

**Comment by doegox** [comment]
`dump_mfu` is for MIFARE Ultralight cards, not MIFARE Classic

By default `chamtool.py` doesn't output anything, try instead
```
python chamtool.py -p /dev/chameleon -v
```

**Comment by geo-rg** [comment]
@ykpe Did this solve your problem?
