### ISSUE TITLE
MyFareMonitor As debugdevice for ChameleonMini

### ISSUE THREAD

**Issue by AndreasBujok** [emsec/ChameleonMini#87]
Hi,

i've wriiten a "MyFareMonitor" to dive more in detail on MyFare Classic and ChameleonMini.
I've used it to understand the technic of RFID and it helps me very well.

See https://github.com/AndreasBujok/MyFareMonitor

@Kasper & Oswald 
If is the wrong place, please delete these post.

Have a nice day
Andreas

**Comment by geo-rg** [comment]
Thank you for sharing this, @AndreasBujok - I think it is the right place here, so people will find this in the closed issue tab.

**Comment by geo-rg** [comment]
We will soon add a list of add-ons, which will feature your project, on the GitHub wiki page.
