### ISSUE TITLE
Replacement for AT45DB081D-SSU

### ISSUE THREAD

**Issue by theforcedk** [emsec/ChameleonMini#9]
Hi

It seems that AT45DB081D-SSU is not manufactured anymore: http://export.farnell.com/adesto-technologies/at45db081d-ssu/ic-dataflash-8mbit-serial-8soic/dp/1455038

Would this work as a direct replacement? http://download.siliconexpert.com/pdfs/2014/5/4/13/28/7/641/adesto_/manual/9ds-45db081e_028.pdf

This: http://www.adestotech.com/pcn/dfreplacement.pdf - seems to suggest that it might, but if I compare the two here: http://export.farnell.com/webapp/wcs/stores/servlet/CompareProductsDisplay?catalogId=15001&langId=71&storeId=10152&catentryId=64576771,67382491&pageType=PLP

I see that the newer chip doesn't have a Serial interface, only SPI and that the memory type is Serial flash and not Flash.

Thanks

**Comment by david-oswald** [comment]
Hi, this should work (assuming you checked that the command set is standard and identical), we'd appreciate if you'd give it a try and post the result.

**Comment by theforcedk** [comment]
Replacement appears to be working fine :) (close again)
