### ISSUE TITLE
chamtool.py giving error when trying start it 

### ISSUE THREAD

**Issue by jandresg** [emsec/ChameleonMini#93]
cd into the appropriate folder and try to launch ... would it happen to be the version of python that I'm using? ... also I'm working on a Mac

> $ python ./chamtool.py -p /dev/cu.usbmodemFA271 -v
>   File "./chamtool.py", line 14
>     print(formatString.format(timeString, text), file=sys.stderr)
>                                                                                  ^
> SyntaxError: invalid syntax
>

**Comment by skuep** [comment]
Chamtool is written in Python 3, It looks like you are using Python 2.

**Comment by geo-rg** [comment]
Does this solve your problem, @jandresg ?
