### ISSUE TITLE
Use Chamelon mini for writing NFC Tags

### ISSUE THREAD

**Issue by poloh11** [emsec/ChameleonMini#96]
Hello,
Do you think that it would be possible to use the Chameleon to write NFC Tags and especially  Classic Mifare 1K ?
Thank you for your answers
Paul

**Comment by geo-rg** [comment]
This is possible. But: You need to know the keys of the MiFare Classic. Also, there is no code for this. So you need to write the code for the Chameleon in reader mode. For this, you can start with looking at the code in Firmware/Chameleon-Mini/Application/Reader14443A.c
